spring:
   mail:
    default-encoding: UTF-8
    host: mail.aate.gob.pe
    username: alertaplicaciones
    password: alerta$2018
    port: 587
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          auth: true
          starttls:
            enable: true       
            required: true 
          ssl:
            trust: mail.aate.gob.pe    
    protocol: smtp
    test-connection: false
    
    